### ISSUE TITLE
[libi86 20191224] testsuite: 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 failed

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/libi86#1]
Building libi86 after https://github.com/tkchia/build-ia16/issues/10 was resolved resulted in this. This is on a Debian 11 (testing) amd64 host.

[testsuite.log](https://github.com/tkchia/libi86/files/4150155/testsuite.log)

Here's a sample part of that log:

```
## ---------------------- ##
## Detailed failed tests. ##
## ---------------------- ##

#                             -*- compilation -*-
2. metacheck.at:23: testing dosemu ...
../../libi86/tests/metacheck.at:25: $DOSEMU --version
stderr:
stdout:
dosemu2-2.0pre8-20200130-1475-gb2414e9c7
Revision: 5174
../../libi86/tests/metacheck.at:26: (
  rm -f a.log && \
  ulimit -t 60 && \
  $DOSEMU -dumb >a.log \
    "$abs_srcdir"/hello-lfn.com </dev/null && \
  test -f a.log && \
  "$abs_srcdir"/postproc-stdout.sh <a.log && \
  rm a.log
)
stderr:
unrecognized argument: /home/evln/coding/proj/build-ia16/build-libi86/../libi86/tests/hello-lfn.com

For passing DOS command use -E
```

This seems to be due to a too new dosemu2.

**Comment by ecm-pushbx** [comment]
This is the revision at https://github.com/ecm-pushbx/dosemu2/commit/b2414e9c7 which is based on https://github.com/ecm-pushbx/dosemu2/commit/ee61aa7b3b2e188b8d61be354ee8934ac6118bba

**Comment by ecm-pushbx** [comment]
https://github.com/stsp/dosemu2/commit/ee61aa7b3b2e188b8d61be354ee8934ac6118bba

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Thanks for the report.  Actually I am currently using the original `dosemu` 1 to do testing, mainly because `dosemu2` does not have a designated stable version yet.

For now, you can try to skip the tests for `libi86` and go straight to doing an installation:
```
(cd build-libi86 && make install)
```
Meanwhile I will also see how I can update the build process to handle this scenario.

Thank you!

**Comment by ecm-pushbx** [comment]
Thanks, I did that and now ./build.sh extra seems to succeed!
