### ISSUE TITLE
[Feature request] dir.h with searchpath

### ISSUE THREAD

**Issue by ecm-pushbx** [tkchia/libi86#12]
I'm working on trying to run and eventually build INTERCEPT, which [I uploaded to the server here](https://pushbx.org/ecm/test/20211110/PC%252FPROGRMNG%252FINTERC2.ZIP) (found via the archives listed [in this RC.SE answer](https://retrocomputing.stackexchange.com/questions/22212/are-there-any-other-historical-traces-of-the-earlier-versions-of-the-alternate-m/22213#22213)). I managed to massage INTERPRE to compile. I don't know yet whether it will work but the last edit I made was to delete a call to `searchpath` which apparently is included from `dir.h`. It appears that this function and header are not yet supported by libi86.

**Comment by ecm-pushbx** [comment]
This is the revision that I deleted the function call to make interpre build: https://hg.pushbx.org/ecm/interc2/rev/0f2e2f585370

I tested in qemu running the most recent FreeDOS kernel. The new interpre.exe appears to work as intended. (Obviously, the data file must be in the current directory to have the program find it.)

The way that INTERCEPT hooks interrupts is absurd, it seems to hook all hooked interrupts with a single handler. Then it detects which one to chain to from the `CDh xxh` instruction found at the caller's `cs:ip`. If no such instruction is found [it unhooks every handler and executes `exit(-1)`](https://hg.pushbx.org/ecm/interc2/file/0f2e2f585370/INTERCEP.C#l127) which did happen to occur somewhere in DOS on [my 2019 November dosemu2 build](https://github.com/dosemu2/dosemu2/discussions/1549) running a current FreeDOS kernel. This is the interrupt handler dump after INTERCEPT has installed its handlers:

```
-di 10 l 14
int 10 1F25:01FA
int 11 1F25:01FA
int 12 1F25:01FA
int 13 1F25:01FA
int 14 1F25:01FA
int 15 1F25:01FA
int 16 1F25:01FA
int 17 1F25:01FA
int 18 1F25:01FA
int 19 1F25:01FA
int 1A 1F25:01FA
int 1B 0070:0203
int 1C F000:F11E
int 1D F000:F11F
int 1E 0070:011E
int 1F C000:0400
int 20 1F25:01FA
int 21 1F25:01FA
int 22 0390:7F76
int 23 02EB:063F
```

To get to the point I could dump this I had to massage the debugger some. From DOS:

```
A:\>ldebug.com intercep.exe lclock.com /o
-r dco or= 4808
```

This enables serial I/O, enables rawinput, and enters always InDOS mode. From the serial terminal:

```
lDebug connected to serial port. Enter KEEP to confirm.
= keep
-s dpr+1000:0 FFFF B8 80 16 CD 2F
1390:646D  84 C0 74 0A F6 06 7D 01-02 75 03 FB F4 90 C3 B8 ..t...}..u......
1390:7700  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00 ................
0002 matches
```

This searches for the idle callout in the debugger's code segment.

```
-u 1390:646D
1390:646D B88016            mov     ax, 1680
1390:6470 CD2F              int     2F
1390:6472 84C0              test    al, al
1390:6474 740A              jz      6480
1390:6476 F6067D0102        test    byte [017D], 02
1390:647B 7503              jnz     6480
1390:647D FB                sti
1390:647E F4                hlt
1390:647F 90                nop
1390:6480 C3                retn
1390:6481 B82020            mov     ax, 2020
1390:6484 AB                stosw
1390:6485 B03A              mov     al, 3A
1390:6487 AA                stosb
1390:6488 BA6EB5            mov     dx, B56E
1390:648B 89F9              mov     cx, di
-r word [1390:6470]
WORD [1390:6470] 2FCD  :9090
```

This patches out the int 2F.1680 call by the debugger's idle function. I'll probably add an option flag to do the same soon.

```
-bp at ri21s:ri21o when value ah in 1A, 4E, 4B
-g
```

This hooks the original int 21h entrypoint with a conditional permanent breakpoint. With the debugger patched not to call int 2Fh and running via serial I/O (that is, not calling int 10h or int 16h) we can actually debug INTERCEPT.

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

> It appears that this function and header are not yet supported by libi86.

Indeed, `<dir.h>` and `searchpath` are not yet supported by `libi86`.  I will see if I can get around to implementing it, though it will probably not be a high priority (I am gearing more towards Open Watcom compatibility first, before working on more Borland C specific stuff).

Anyway, `intercept` does look like a pretty interesting program.  Incidentally I came across Diomidis Spinellis's [`trace`](https://www.spinellis.gr/sw/ports/trace/) a while back, but I believe `trace` only logs MS-DOS syscalls.

> Then it detects which one to chain to from the `CDh xxh` instruction found at the caller's `cs:ip`.

That is a bit too fragile, I think. :neutral_face: 

Thank you!

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

This feature request reminds me: I should probably also update `newlib-ia16` and `libi86` 's file name routines to properly handle multi-byte characters (https://github.com/tkchia/newlib-ia16/issues/17)...

Thank you!

**Comment by tkchia** [comment]
Hello @ecm-pushbx,

Here goes: https://github.com/tkchia/libi86/commit/54992e509d9ec97596be8704a39cb82e78471528 .  Thank you!
