### ISSUE TITLE
Mkdir defined differently on Watcom / TurboC++ 3.0

### ISSUE THREAD

**Issue by andrewbird** [tkchia/libi86#16]
Hello,
  I'm working on making https://github.com/FDOS/move compilable with Gcc-ia16 / Watcom[0] and Turbo C++. I'm finding that both Watcom and TurboC++ provide the `mkdir(const char *name)` function it uses. From what I can see libi86 doesn't and gcc-ia16 seems to fallback to some Unix version that expects an additional mode parameter. Is libi86 likely to get a DOS version of `mkdir()` or should I just make some local function that uses `intdos()` to implement?

Thank you!

[0] https://open-watcom.github.io/open-watcom-v2-wikidocs/clib.html#mkdir

**Comment by tkchia** [comment]
Hello @andrewbird,

> Is libi86 likely to get a DOS version of `mkdir()`

Hmm... it probably should. :neutral_face:  Sorry for not noticing this problem earlier.

I will see how I can at least implement a 1-argument `_mkdir` (with underscore) and have it available through `<direct.h>`.  (The Unix-style, 2-argument `mkdir` is supposed to be defined in a different header, `<sys/stat.h>`.)  It will be best if `mkdir` can also be declared to allow for either 1 argument or 2-arguments, but that may be hard to do in C.

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
   Thanks for considering this request. In the meantime I made some little temporary functions to get me by. To be honest there was lots to change within the `move` repository, see my branch https://github.com/andrewbird/move/tree/build-01, much more than I'd like so there'll have to be lots of testing when I'm finished I guess.
I almost have it linking now with gcc-ia16, just some references remain to `chmod()` and `access()`. I've already removed some uses of the TurboC specific `_chmod()` and its local replacement function for Watcom in favour of `[gs]etfileattr()`. This remaining use seems to want to twiddle both the read and write protect bits, which is a little unusual on DOS.

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia, 
 That's great progress with libi86 adding DOS compatible mkdir() rmdir(), which allowed me to remove my local functions. One more thing, do you think that access() and chmod() from newlib should work on DOS?
Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> This remaining use seems to want to twiddle both the read and write protect bits, which is a little unusual on DOS.

`chmod (, )` (sans underscore) accepts Unix-style permission bits.  `S_IREAD | S_IWRITE` &mdash; if that is what you are referring to &mdash; means to give the file owner _permission_ to read and write the file.

> do you think that access() and chmod() from newlib should work on DOS?

I found that `access (, )` and `chmod (, )` were not implemented in Newlib, so I have now added them in.  At the moment these routines do not really do much, other than to twiddle the DOS read-only attribute.  Unfortunately the other MS-DOS attributes do not seem to have analogues in the Unix permission scheme.

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
> chmod (, ) (sans underscore) accepts Unix-style permission bits. S_IREAD | S_IWRITE — if that is what you are referring to 

Yes, exactly that. It would seem that TurboC and Watcom translate `S_IREAD` and `S_IWRITE` into some sane permissions for DOS.

> I found that access (, ) and chmod (, ) were not implemented in Newlib, so I have now added them in.

Ahh good, that explains why my attempt to use them failed at link time.

I have to go out today, but I'll give them a try later.

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
   My trip out was cancelled so I got to test your latest straight away. The new functions `access()` and `chmod()` are linking fine and so allowed me to drop two more of my commits.

I notice that the size of the output .exe is quite a lot larger than the others
|compiler|.exe size|
| ----- | ---- |
| Gcc | 73616 |
|Watcom | 37150 |
|TurboC |33076|

I'm attached the .map file just in case you think there's something obviously wrong 
[map.zip](https://github.com/tkchia/libi86/files/7970449/map.zip)

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

Hmm... the bloat _might_ be because I recently enabled multi-byte character support (at the userland level) for Newlib, which causes `printf` and friends to rope in some additional code and data.  I probably should see how I can pare down on this bloat.

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
  I'll close this now as you've fixed the problem for me. Regarding the bloat, I'll probably look at using one of the printf replacements that other FDOS projects use to reduce size as there's really no need to use printf just to assemble character strings.

Thank you for all your help!

**Comment by tkchia** [comment]
Hello @andrewbird,

> It seems a significant part of the code bloat was due to the use of `scanf("%-4s")`.

Well, that is cool to know.  Thank you!
