### ISSUE TITLE
Allow running libi86 test suite outside of libi86 build process (on a pre-installed copy of libi86)?

### ISSUE THREAD

**Issue by tkchia** [tkchia/libi86#18]
Andrew Bird asks at https://github.com/dosemu2/dosemu2/issues/1673#issuecomment-1154202736 :

> I'm wondering if it is possible to run the libi86 test suite against the packaged installed libl86 / ia16-elf-gcc rather than building the library first?

**Comment by tkchia** [comment]
Implemented with commits a825ed7a34731266eeaca4271de7e64e3e5b190b, d401d46758b0217ac00979e2b19318b6c2163a2d, 52775572f63a84c7d7a0df9a53df2b2e413c4097, and ce952215ca66023df9cc43db89c3d9af63c8e825.

**Comment by andrewbird** [comment]
Hello @tkchia,
 Thanks for working on this. I've now installed the deb, but I don't know how to run the tests. Here's what I have on Ubuntu Focal
~~~
ajb@polly:~$ dpkg -L libi86-testsuite-ia16-elf
/.
/usr
/usr/ia16-elf
/usr/ia16-elf/libexec
/usr/ia16-elf/libexec/libi86
/usr/ia16-elf/libexec/libi86/tests
/usr/ia16-elf/libexec/libi86/tests/atlocal.in
/usr/ia16-elf/libexec/libi86/tests/capture-ack.s
/usr/ia16-elf/libexec/libi86/tests/capture-gcc.S
/usr/ia16-elf/libexec/libi86/tests/config.status.tests
/usr/ia16-elf/libexec/libi86/tests/hello.com
/usr/ia16-elf/libexec/libi86/tests/postproc-console.sh
/usr/ia16-elf/libexec/libi86/tests/postproc-stdout.sh
/usr/ia16-elf/libexec/libi86/tests/testsuite
/usr/share
/usr/share/doc
/usr/share/doc/libi86-testsuite-ia16-elf
/usr/share/doc/libi86-testsuite-ia16-elf/changelog.Debian.gz
/usr/share/doc/libi86-testsuite-ia16-elf/copyright
~~~
I took a guess that `testsuite` would be the file to kick things off, but it seems not. Where are the actual tests themselves?
~~~
ajb@polly:~$ /usr/ia16-elf/libexec/libi86/tests/testsuite
testsuite: error: needed config file missing: atconfig or tests/atconfig
~~~

Sorry for not understanding!

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

The tests are all inside the `testsuite` script &mdash; this is why it is so big, at about 177.7 MiB. :slightly_smiling_face: 

You can run it like this:

> `$ mkdir testing/`
> `$ /usr/ia16-elf/libexec/libi86/tests/testsuite -C testing --x-installcheck \`
> `    --x-test-underlying -j4 --x-with-dosemu=`...

This will basically turn the `testing/` directory into a sort of rump "build tree", and run the regression tests inside the directory.

You can also do

> `$ /usr/ia16-elf/libexec/libi86/tests/testsuite --help`
> `$ /usr/ia16-elf/libexec/libi86/tests/testsuite --list`

(I should really document all this properly at some point, but I wanted to get something working out first.)

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia ,
 That's really good! I'll see if I can modify the dosemu2 testsuite to use it now
~~~
ajb@polly:~/Desktop$ /usr/ia16-elf/libexec/libi86/tests/testsuite -C testing --x-installcheck --x-test-underlying 93
testsuite: running /usr/ia16-elf/libexec/libi86/tests/config.status.tests
config.status.tests: creating tests/atlocal
config.status.tests: executing tests/atconfig commands
testsuite: WARNING: running tests in /home/ajb/Desktop/testing/tests
## ----------------------------------- ##
## libi86 20220618 test suite: libi86. ##
## ----------------------------------- ##
 93: _fstrlen                                        ok

## ------------- ##
## Test results. ##
## ------------- ##

1 test was successful.
~~~

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

Apologies for the rather clunky interface.  Part of the problem is that the GNU Autotest framework is not really meant to work outside of a build tree.  As far as I understand, its main intended use is as part of a `make check` &mdash; and maybe to some extent `make installcheck` &mdash; from inside a project build.

Basically what did in the end, was to add a `--x-installcheck` option to my test suite, doctor the `config.status` file created by GNU Auoconf, and jury-rig the option so that it recreates some sort of "build tree".

By the way, if you wish to remain on a particular version of `libi86` for your tests, you probably want to copy the `libi86-ia16-elf` source package in Launchpad to a repository of your own.  (The `libi86-ia16-elf` source package is also responsible for producing the `libi86-testsuite-ia16-elf` output package.)

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
   I've been experimenting with this new way of running the test suite. Strangely I'm finding it very slow, it probably takes about 2.5 times longer than building and testing as before. A single invocation of all tests took 1500 seconds
~~~
<snip>

<libi86/string.h> tests

 89: _fmemcmp                                        ok
 90: _fmemcpy                                        ok
 91: _fmemmove                                       ok
 92: _fmemset                                        ok
 93: _fstrlen                                        ok

## ------------- ##
## Test results. ##
## ------------- ##

All 93 tests were successful.
ok (1573.37s)

----------------------------------------------------------------------
Ran 1 test in 1573.370s

OK
~~~


If I run just bios_memsize, it takes 18 secs.
~~~
testsuite: WARNING: running tests in /tmp/test-imagedir/libi86_test-xxxx/tests
## ----------------------------------- ##
## libi86 20220618 test suite: libi86. ##
## ----------------------------------- ##
 11: _bios_memsize                                   ok

## ------------- ##
## Test results. ##
## ------------- ##

1 test was successful.
ok ( 17.84s)

----------------------------------------------------------------------
Ran 1 test in 17.843s

OK
~~~

That seems like a really long time to compile/run this
```c
#include <stdlib.h>                                                           
#include <bios.h>                                                               
#ifndef __cplusplus                                                             
# error                                                                         
#endif                                                                          
int main (void)                                                                 
{                                                                               
  unsigned short kb = _bios_memsize (), kb2;                                    
  __asm ("{movw %1:0x13, %0|mov %0, %1:0x13}"                                   
         : "=r" (kb2)                                                           
         : "Q" (__builtin_ia16_selector (0x40)));                               
  if (kb != kb2)                                                                
    abort ();                                                                   
  return 0;                                                                     
}
```

As a test, I modified the dosemu startup script to log start and stop times, as you can see it's about 2 secs on the same test
~~~
Sun Jun 19 13:55:13 BST 2022                                                    
Sun Jun 19 13:55:15 BST 2022
~~~

Perhaps you have some ideas on where the excess time is being spent?

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
  Sorry I forgot to mention there seems to be a problem with passing dosemu options. If I pass

`--x-with-dosemu-options="-f /tmp/test-imagedir/dosemu.conf -n --Fimagedir /tmp/test-imagedir"`

Dosemu actually sees this when trying to resolve the paths (note the `-f` is gone, but a leading space is there). I'm pretty sure that Dosemu is being passed a single string instead of an array of strings.

` /tmp/test-imagedir/dosemu.conf -n --Fimagedir /tmp/test-imagedir`

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> Perhaps you have some ideas on where the excess time is being spent?

Did you pass the `--x-test-underlying` option, as before?  Again, this will focus on stress-testing the underlying DOS emulation rather than stress-testing `libi86` itself, and should take less time.

---

> Dosemu actually sees this when trying to resolve the paths (note the `-f` is gone, but a leading space is there). I'm pretty sure that Dosemu is being passed a single string instead of an array of strings.
> 
> `/tmp/test-imagedir/dosemu.conf -n --Fimagedir /tmp/test-imagedir`

I could not reproduce this.  The logs on my end suggest that `dosemu` did indeed see the correct options:
```
$ /usr/ia16-elf/libexec/libi86/tests/testsuite -C ... --x-installcheck \
  --x-with-dosemu-options="-f /tmp/test-imagedir/dosemu.conf -n --Fimagedir /tmp/test-imagedir" \
  1-10 --x-test-underlying
...
$ less .../testsuite.dir/03/testsuite.log
...
stderr:
ERROR: --Fimagedir: /tmp/test-imagedir does not exist
...
@@ -1,2 +1 @@
-Hello world!
```

Perhaps there was something else munging the command line options on your end?

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
   Previously I used to set TESTSUITEFLAGS in the environment with `--x-test-underlying` , now I'm specifying it on the command line instead.

> Perhaps there was something else munging the command line options on your end?

I think you are correct, I ran it successfully from the command line too.

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

Ah, OK. :slightly_smiling_face:  As you probably know, the Bourne shell expands `$TESTSUITEFLAGS` in a quite different way from how `make` expands `$(TESTSUITEFLAGS)`.

I guess one way to replicate the `make` behaviour is to use something like `eval` (!).  But I guess a better way might be to directly specify the options to the `testsuite` script as an array &mdash; I see your `test/test_dos.py` already does that in several places anyway. :slightly_smiling_face: :slightly_smiling_face: 

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

In this case the command line array will most probably look something like this:
```
['/usr/ia16-elf/libexec/libi86/tests/testsuite', '-C', '...', '--x-installcheck',
  '--x-test-underlying', '--x-with-dosemu=/usr/bin/dosemu',
  '--x-with-dosemu-options=-f /tmp/test-imagedir/dosemu.conf -n --Fimagedir /tmp/test-imagedir',
  ...]
```
Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,

> '--x-with-dosemu-options=-f /tmp/test-imagedir/dosemu.conf -n --Fimagedir /tmp/test-imagedir',

Indeed it does
```python
    dosemu = self.topdir / "bin" / "dosemu"                                     
    options = '-f {0}/dosemu.conf -n --Fimagedir {0}'.format(self.imagedir)     
    args = [                                                                    
        '--x-installcheck',                                                     
        '--x-test-underlying',                                                  
        '--x-with-dosemu=%s' % dosemu,                                          
        '--x-with-dosemu-options=%s' % options,                                 
    ]                                                                           
```

I really don't understand why quotes are not needed around `-f /tmp/test-imagedir/dosemu.conf -n --Fimagedir /tmp/test-imagedir`, but hey ho!

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> I really don't understand why quotes are not needed around `-f /tmp/test-imagedir/dosemu.conf -n --Fimagedir /tmp/test-imagedir`, but hey ho!

Well, yes &mdash; I was also mighty confused by all the shell quoting rules and whatnot several years back. :neutral_face: 

Anyway, as a sort of attempt at explanation of my understanding...

The `testsuite` script itself does _not_ need to see the double quotes in its parameters, but it _does_ need the `--x-with-dosemu-options=`_opts_ string to be passed as a single parameter word.  So you need to somehow quote the escape any spaces inside _opts_, so that the caller shell (not the `testsuite`) can pass it as one parameter.

Basically if, from a parent shell, you say
  * `./prog foo bar`
 
then the program `./prog` will see `argv[1]` = `foo` and `argv[2]` = `bar`.

But if you say
  * `./prog "foo bar"`
  * or `./prog foo" "bar`
  * or `./prog foo' bar'`
  * or `./prog foo\ bar`

etc. then the program `./prog` will see a single string `foo bar` in `argv[1]`.  (The shell will not pass the quote characters to `./prog`.  The `bash` and `dash` man pages should give further detail on all the quoting rules.)

Python's `subprocess.check_call(`...`)`, of course, uses a totally different method to control how the arguments are split up &mdash; namely, you directly control what the callee's `argv[]` looks like. :slightly_smiling_face: 

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

(Unfortunately, this also means that at the moment there is still no good way to tell `--x-with-dosemu-options=` to pass an argument to `dosemu` which itself contains spaces. :thinking: )

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

Thanks for the heads-up!  Let me know if you still encounter any problems.

As mentioned, if you want to stay on a particular version of the `libi86` packages, you can ask Launchpad to copy out the version of the source package to your own PPA.

Thank you!
