### ISSUE TITLE
Dos.h

### ISSUE THREAD

**Issue by toncho11** [tkchia/libi86#20]
Hi,

I see you provide a ported version of dos.h, but wihout delay(), sound() and nosound(), right? But then these are exactly the functions that I need.

**Comment by andrewbird** [comment]
Try including the header `i86.h`

**Comment by tkchia** [comment]
Hello @toncho11, hello @andrewbird,

Including `<dos.h>` should also work &mdash; `<dos.h>` itself includes `<i86.h>`, which declares these functions.

Thank you!

**Comment by toncho11** [comment]
But they are implemented or just declarations?

**Comment by tkchia** [comment]
Hello @toncho11,

They are defined.  If you include `-li86` (when compiling for the MS-DOS target) on the linker command line, you should be able to get these functions.

In fact `sound (`_freq_`)` has an optimized implementation for cases where _freq_ is a compile-time constant.

Thank you!
