### ISSUE TITLE
Test suite batchfiles are generated with Unix line endings

### ISSUE THREAD

**Issue by andrewbird** [tkchia/libi86#3]
I've been trying to run the test suite under MS-DOS 6.22, but I'm seeing more failures than under FDPP. I believe at least some of these are because the generated batchfiles have Unix line termination see below
~~~
ajb@polly:/clients/common/dosemu2.git/test-imagedir/i86root.git$ sod ./build-29061/tests/testsuite.dir/1/x.bat
000000 40 65 63 68 6f 20 6f 66 66 0a 63 6c 73 0a 61 2e  >@echo off.cls.a.<
000010 65 78 65 0a 69 66 20 6e 6f 74 20 65 72 72 6f 72  >exe.if not error<
000020 6c 65 76 65 6c 20 31 20 67 6f 74 6f 20 6f 6b 0a  >level 1 goto ok.<
000030 67 6f 74 6f 20 64 6f 6e 65 0a 3a 6f 6b 0a 63 61  >goto done.:ok.ca<
000040 70 74 75 72 65 2e 65 78 65 20 3e 61 2e 6c 6f 67  >pture.exe >a.log<
000050 0a 69 66 20 65 72 72 6f 72 6c 65 76 65 6c 20 31  >.if errorlevel 1<
000060 20 64 65 6c 20 61 2e 6c 6f 67 0a 3a 64 6f 6e 65  > del a.log.:done<
000070 0a                                               >.<
~~~

which in my case leads to missing output.

~~~
stderr:                                                                         
ERROR: unknown window sizes li=0  co=0, setting to 80x25                        
--- expout      2020-09-21 11:53:26.074930870 +0100                             
+++ /clients/common/dosemu2.git/test-imagedir/i86root.git/build-29061/tests/testsuite.dir/at-groups/1/stdout    2020-09-21 11:53:28.990825007 +0100
@@ -1,3 +1,10 @@                                                                
-w00t                                                                           
-                                                                               
-w0000t                                                                         
+off                                                                            
+cls                                                                            
+a.exe                                                                          
+if not errorlevel 1 goto ok                                                    
+goto done                                                                      
+:ok                                                                            
+capture.exe                                                                    
+if errorlevel 1 del a.log                                                      
+:done                                                                          
+^M                                                                             
1. metacheck.at:19: 1. Console output testing (metacheck.at:19): FAILED (metacheck.at:21)
~~~

Please ignore the value of the test number as I've hacked up some of the test scripts so that I can run just a single test.

**Comment by tkchia** [comment]
Hello @andrewbird,

I have pushed some commits which should resolve the problem.

I also added some options you can pass to the test suite (see my updated `README.md`).  In particular the `--x-test-underlying` option means to concentrate more on testing the underlying MS-DOS emulation, and will skip many of the subtests that are less relevant for this use case.

Thank you!

**Comment by andrewbird** [comment]
Sorry I forgot to say, thank you for the new `--x-test-underlying` option etc. I've been tweaking one of your scripts at testtime to add in the Dosemu options I need (`-f /clients/common/dosemu2.git/test-imagedir/dosemu.conf -n --Fimagedir /clients/common/dosemu2.git/test-imagedir`), is there a better way to accomplish this now?

Until now I've been running `tests/travis_build_and_check.sh` to start the tests. I think I'm probably at the point that I need to create my own script to start things. I see that you initiate the tests yourself via a Makefile, is there a script that I can call directly instead whilst passing in the new options?

Thank you!

**Comment by andrewbird** [comment]
So I now read the updated readme.md, not just the diff! I now see how to pass the test options to make, so please ignore the second question.

Thanks!

**Comment by andrewbird** [comment]
I used the new options you added and created a draft PR for Dosemu2. Do think you could add a `--x-with-dosemu-options="-xxx -yyy -zzz"`  to TESTSUITEFLAGS please? What I'm looking for is the ability to add the `-f /clients/common/dosemu2.git/test-imagedir/dosemu.conf -n --Fimagedir /clients/common/dosemu2.git/test-imagedir` to each Dosemu invocation so that I can specify where the disks and config live. If that's done I can drop the commit that does a horrid in-place sed edit on local.at

Thank you!

**Comment by andrewbird** [comment]
I forgot to provide the link to the PR https://github.com/dosemu2/dosemu2/pull/1286

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird ,

It is done now: https://github.com/tkchia/libi86/commit/b9c9cbe34980ab0e93c33f6d84a62a2cbb2a715a .  Thanks!

**Comment by andrewbird** [comment]
Thank you, the new option looks great!
