### ISSUE TITLE
_dos_setfileattr() failing on MS-DOS 6.22

### ISSUE THREAD

**Issue by andrewbird** [tkchia/libi86#4]
There's just one test failing for me now with Dosemu2 and MS-DOS 6.22
~~~
21. dos.h.at:326: 21. _dos_setfileattr (dos.h.at:326): FAILED (dos.h.at:327)
~~~

I've attached a tarred up build/tests directory 
[libi86fail.tar.gz](https://github.com/tkchia/libi86/files/5256410/libi86fail.tar.gz)

**Comment by tkchia** [comment]
Hello @andrewbird,

Thanks!  This should be fixed now (https://github.com/tkchia/libi86/commit/8edd340359318525f13871ccfe4f553b374a003d), and the test should now pass on MS-DOS itself.  It seems that my test suite is triggering some obscure behaviours of the various DOS kernels.

**Comment by andrewbird** [comment]
Thank you, this is now fixed!
