### ISSUE TITLE
Feature request:  _fullpath, _splitpath, _makepath etc

### ISSUE THREAD

**Issue by andrewbird** [tkchia/libi86#7]
I'm looking at getting FDOS/more compiling with ia16-elf-gcc, but I've reached a problem as there some functions missing. I'm not familiar with these functions myself, but Watcom has them defined as:
```c
_WCRTLINK extern char    *_fullpath( char *__buf, const char *__path, __w_size_t __size );
_WCRTLINK extern void    _splitpath( const char *__path, char *__drive,   char *__dir, char *__fname, char *__ext );
_WCRTLINK extern void    _makepath( char *__path, const char *__drive, const char *__dir, const char *__fname, const char *__ext );
```
Is that something you'd consider adding?

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> Is that something you'd consider adding?

Yep; the goal, as always, is to be compatible enough with the Open Watcom runtime to be useful. :-)

I will look into how to implement the `_fullpath`, `_splitpath`, and `_makepath` functions into `libi86`.  (I notice that `newlib-ia16` has a `realpath` function in its Linux port, so I will see if I can use that as a starting point.)

Thank you!

**Comment by andrewbird** [comment]
Thank you very much for looking at this!

**Comment by andrewbird** [comment]
Hi @tkchia I see you've been working on `_splitpath()`, thank you very much for that! My work on FDOS projects is continuing and I'm finding a few more missing functions. Would you like me to document them here, or elsewhere?

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> I see you've been working on `_splitpath()`, thank you very much for that! 

Thanks!  For now you need to include `<libi86/stdlib.h>` to get it --- maybe something like
```
#ifdef __GNUC__
# include <libi86/stdlib.h>
#endif
```
This is a bit clunky, so I am trying to see if there is a good way to add "extensions" to the standard header files, without disturbing the headers in the original C runtime (Newlib).

> My work on FDOS projects is continuing and I'm finding a few more missing functions. Would you like me to document them here, or elsewhere?

That is up to you --- just let me know about them. :-)

Thank you!

**Comment by andrewbird** [comment]
Here's a little table I'm keeping for myself
                                                                           
Program|Turbo C|Watcom DOS|Watcom Cross|GCC Cross|Kitten Submodule|Has Tests    
-------|-------|----------|------------|---------|----------------|---------    
sort|yes|yes|yes|yes|yes|yes                                                    
more|yes|yes|yes|no|yes|no                                                      
find|yes|yes|yes|no|yes|no                                                      
        
-----------------------------------------                                       
Functions we need but GCC doesn't have yet                                      
- [ ] `_makepath()`                                                              
- [x] `_splitpath()`                                                             
- [ ] `_dos_findfirst()`                                                         
- [ ] `_dos_findnext()`                                                          
- [ ] `_dos_setdrive()`
- [ ] `ltoa()` // workaround using sprintf in-place but undesirable as all the other printfs have been remove for size reasons

**Comment by tkchia** [comment]
Hello @andrewbird,

`_dos_findfirst` and `_dos_findnext` may take a while to implement --- I need to set up some infrastructure so that these can work correctly when under DPMI.

Thank you!

**Comment by andrewbird** [comment]
Thank you for the great help you been so far! I'll probably see if I can use some simple local replacements in the meantime as I don't need DPMI here.

Thanks again!

**Comment by tkchia** [comment]
Hello @andrewbird,

Thank you!  In any case, I just got `_dos_findfirst` and `_dos_findnext` working.

**Comment by andrewbird** [comment]
Thank you very much for this. Sorry to be a pain, but since I now get to the linking stage I've just noticed there are two more missing functions `getcwd` and `chdir`. By poking around in the installation I see this, so I don't think they are really missing but my linking problem.

~~~
ajb@polly:/usr/ia16-elf/lib$ ar -t libdos-s.a | grep getcwd
dos-getcwd.o
ajb@polly:/usr/ia16-elf/lib$ ar -t libdos-s.a | grep chdir
dos-chdir.o
~~~
and this
~~~
ajb@polly:/usr/ia16-elf/include$ grep getcwd */*
sys/unistd.h:char *  _EXFUN(getcwd, (char *__buf, size_t __size ));
~~~

My current compilation line is
~~~
ia16-elf-gcc -Wall -fpack-struct -mcmodel=small -o find.exe find.c find_str.c ../kitten/kitten.c -li86 
~~~

What should I add to the gcc command line to link those in, I tried `-ldos-s` but that didn't help?

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

Thanks for the report!

`dos-getcwd.o` and `dos-chdir.o` are in the underlying C library, i.e. [`newlib-ia16`](https://github.com/tkchia/newlib-ia16), so by right you should not need to specify any extra linker options.

However I see that the implementations are still not very complete:
  * they do not factor in DOS drive letters
  * plus they are also named wrong (`_getcwd` and `_chdir`, instead of `getcwd` and `chdir` --- hence the linker errors you got).

I will work on fixing these.

Thank you!

**Comment by andrewbird** [comment]
Thanks for looking at this too! I've also just successfully compiled FDOS/more now that you've added `_dos_find*()`

Thanks again!

**Comment by andrewbird** [comment]
Thank you, find now links properly!

**Comment by andrewbird** [comment]
Hi @tkchia I'm looking at FDOS/label now, but it seems to want to install a ctrl-c handler. I can see that it wants to use Watcom's `_dos_setvect()`, to setup a simple handler with just exit(0) inside. I can probably set the handler by `intdos()`, but is a gcc function okay to use as an interrupt handler, as I note the non Turbo C definition is?
~~~
void far _interrupt ctrlc_hndlr()
~~~

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> is a gcc function okay to use as an interrupt handler, as I note the non Turbo C definition is?

Hmm... unfortunately `gcc-ia16` does not support interrupt routines yet. :-|  This will probably take a _really_ good while to properly implement and test, since there are quite a number of details to get right.  Hopefully I can start implementing this soon.

(Anyway, it seems to me that `label.c` might _also_ need some fixing and cleaning up to build and run properly with the Watcom toolchain.  In particular, I am not quite sure if calling `exit(.)` from within an ISR is that safe --- is there any guarantee that the ISR will run on the program's own stack?.  The main use of the ISR is to make sure the program moves back to the working directory it was started out in: the `exit(.)` triggers a call to `on_exit()`, registered via `atexit(.)`.)

Thank you!

**Comment by andrewbird** [comment]
> Anyway, it seems to me that label.c might also need some fixing and cleaning up to build and run properly with the Watcom toolchain.

Oh yes, it's a work in progress!

>In particular, I am not quite sure if calling exit(.) from within an ISR is that safe --- is there any guarantee that the ISR will run on the program's own stack?

I also wondered if I should restore the intvec 23 at program end, else it's still pointing at freed memory?

I'm not really a fan of programs calling `exit()` from within functions, I might see if I can return error codes and handle in main() instead.

Thanks for your help again!

**Comment by andrewbird** [comment]
For reference I fixed the compilation problems with watcom. Here is my branch with those https://github.com/andrewbird/label/tree/build-01

make -C src clean ; env COMPILER=gcc ./build.sh

You can try to build with any of COMPILER= tcc-emu, watcom-emu,  watcom or gcc(currently fails)

**Comment by tkchia** [comment]
Hello @andrewbird,

I have been adding some support for an `__attribute__ ((interrupt))` function attribute to `gcc-ia16`.  It is still incomplete though --- you can add this attribute to function declarations, but defining `interrupt` functions does not work yet.

> I also wondered if I should restore the intvec 23 at program end, else it's still pointing at freed memory?

I suspect that this is not a big problem.  The parent process's `int 0x23` vector is [stored in the PSP](http://www.delorie.com/djgpp/doc/rbinter/it/78/13.html), and if `label.exe` exits, we should expect that DOS will restore the parent's `int 0x23` vector from there.

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

OK, I have added some (experimental) support for `__attribute__ ((interrupt))` and a Watcom-compatible `__interrupt` word to `gcc-ia16`, plus a `_dos_setvect (, )` function to `libi86`.  I will see if I can propose a patch to get `label.c` to build under `gcc-ia16` as well.

By the way, regarding `toupper (.)`, I am pretty sure Watcom has such a thing (in `<ctype.h>`), since it is a standard C facility.  If `toupper (.)` is not working, then something is not right.

Thank you!

**Comment by andrewbird** [comment]
Hi @tkchia ,thanks for looking at this. I've been a little busy with other things since I mentioned `_dos_setvect()`, so I've not had the chance to test out your latest changes or finalise my eventual PR to FDOS/label yet. Thanks for the heads-up on `toupper()`, I'll try to get back to label in the coming days, and let you know how things go!

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

Since (as you know) the functions have now been implemented, the needed changes to `FDOS/label` are now upstream, I guess this issue can now be considered resolved.  Feel free to reopen if there are still any problems.  Thank you!

**Comment by andrewbird** [comment]
Cool, thanks!

**Comment by andrewbird** [comment]
Hello @tkchia,
   I'm finally getting to use your new `_dos_getvect()` and `_dos_setvect()` functions. For a Dosemu2 test I'm writing I need to replace the int24 critical error handler with my own non-interactive one that just saves the input value, and returns 3 for 'fail'. Here's the snippet of code I have
```c
volatile int last_int24;

void __far __interrupt (*oldint24)(void);

void __far __interrupt myint24(void)
{
  /* I need to check the input and return 3 here somehow */
}

 int main(int argc, char *argv[])
{ 
  // Setup int24 handler
  oldint24 = _dos_getvect(0x24);
  _dos_setvect(0x24, myint24);

<snip>
```

Here's the int24 page in RBIL http://www.ctyme.com/intr/rb-4112.htm .

Please can you suggest how I should access/set the AH and AL registers from within the interrupt handler `myint24()`?

Thank you!

**Comment by andrewbird** [comment]
I have done this, which seems to work, but it's probably not the most elegant solution and generally I'm not too confident with gnu inline asm, so there might be problems.

```c
void __far __interrupt myint24(void)                                            
{                                                                               
  // Save the input                                                             
  asm volatile(                                                                 
    "nop\n"                                                                     
    : "=a"(last_int24)                                                          
    : /* no input */                                                            
    : /* nothing clobbered */                                                   
  );                                                                            
                                                                                
  // Set the return to 'F'                                                      
  asm volatile(                                                                 
    "movb $0x03, %%al\n" /* 0=Ignore, 1=Retry, 2=Terminate, 3=Fail */           
    : /* no output */                                                           
    : /* no input */                                                            
    : /* nothing clobbered */                                                   
  );                                                                            
}                                                                               
```

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

Probably the most reliable method &mdash; at least for now &mdash; would be to write the whole `myint24` function directly in assembly.  That is either put it in a separate `.S` (or `.s`) module, or write an `asm` statement at file scope, e.g.
```
__asm(
  "myint24:\n"
  ...
  "  iretw"
);

int main(int argc, char *argv[])
{
  ...
}
```

Register inputs and outputs for `interrupt` function definitions are still unimplemented `gcc-ia16` &mdash; I have still not quite decided what form these should take. (Ideally it will either be able to jive well with GCC's optimizer, or be somewhat compatible with Watcom's `union INTPACK` (but probably not both...).)

Thank you!

**Comment by andrewbird** [comment]
That's another very interesting thing, I'll certainly give the asm function at file scope a try.

Thank you!

**Comment by andrewbird** [comment]
Just in case anyone's interested here's what I ended up with

```c
volatile uint16_t int24_ax;

void __far __interrupt myint24(void); /* Prototype */                           
__asm (                                                                         
  "myint24:\n"                                                                  
  "  pushw %bp\n"                                                               
  "  movw  %sp, %bp\n"                                                          
                                                                                
  "  pushw %ds\n"                                                               
  "  pushw 22(%bp)\n"   /* int21 caller's DS on stack */                        
  "  popw  %ds\n"                                                               
  "  movw  %ax, int24_ax\n"                                                      
  "  popw  %ds\n"                                                               
                                                                                
  "  popw  %bp\n"                                                               
                                                                                
  "  movb  $0x03, %al\n" /* 0=Ignore, 1=Retry, 2=Terminate, 3=Fail */            
  "  iretw\n"                                                                   
); 
```

Thanks!

**Comment by andrewbird** [comment]
> Register inputs and outputs for interrupt function definitions are still unimplemented gcc-ia16 — I have still not quite decided what form these should take. 

I'm looking at trying to get FreeDOS share to compile ideally on both Watcom and Gcc cross compilers. Currently share seems to only be compilable by Turbo C and specifically only v 2.01. One issue I'm facing is the interrupt handler
 2f hook. https://github.com/FDOS/share/blob/ac83c16268bfff4c39bd85da192b1f157d05c7a1/share.c#L208 Watcom seems to have a chain interrupt function, but the handler itself still doesn't have access to the current registers when it's called. Did you have any more thoughts about how to implement register access here? And if not, I guess writing it in assembly is the only option, though I suppose that's not that palatable for FreeDOS?

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> Watcom seems to have a chain interrupt function, but the handler itself still doesn't have access to the current registers when it's called.

According to the Open Watcom's _User's Guide_ (page 84 or thereabouts), yes, you _can_ get an interrupt handler written in Watcom C to access registers, by declaring a special argument:

> ```
> #include <i86.h>
> 
> void __interrupt int10( union INTPACK r )
> {
>         ⋮
> }

The function to chain to another ISR is `_chain_intr`, which is documented in the _Open Watcom C Library Reference_.

(I believe you need to call `_chain_intr` directly within your ISR function itself (and not in a callee) &mdash; Watcom implements `_chain_intr` as a normal assembly language routine which depends on `bp` pointing directly at the `union INTPACK`.)

Apparently Borland Turbo C++ 3.0, but not Turbo C 2.01, also has a `_chain_intr` function.  My guess is that it works the same way as Watcom's function, though I have not checked.

Thank you!

**Comment by andrewbird** [comment]
@tkchia, thanks for your great help again! I've now managed to get it compiling with Watcom. As yet I haven't tested it but I am immediately suspicious about the resultant tiny model binary as I get warnings at link stage about relocations. The map file doesn't provide any clue that I can see about what's causing them. I've pushed a branch here https://github.com/andrewbird/share/tree/build-01 if you are interested. The .COM file produced is about 30% larger than the Turbo C one, which is a shame.

On the Gcc-ia16 front, I think I'm short of
- _chain_intr()
- _dos_keep()
- fnmatches()
- and of course the register access within the interrupt handler (unless I try to write assembly)

Thank you!

**Comment by andrewbird** [comment]
Ignore fnmatches() I just saw it's implemented locally!

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

> ```
> ia16-elf-gcc -Wall -fpack-struct -fno-toplevel-reorder -mcmodel=tiny -c share.c -o share.obj -Os
> share.c: In function ‘main’:
> share.c:33:23: error: cannot take address of far function or far static variable
> share.c:33:23: note: use ‘-mcmodel=small’ to allow this
> ```

This is because, as far as `ia16-elf-gcc` is concerned, `handler2f ()` is an external function, and it cannot make any assumptions about which segment `handler2f ()` is actually in.  I implemented a `near_section` function attribute in `gcc-ia16` to cater to such cases &mdash; this attribute tells the compiler that the function is known to be in the default text segment.  You can use it like this:

```
void __far __interrupt __attribute__((near_section)) handler2f(void);
```

Thank you!

**Comment by andrewbird** [comment]
Thanks that compiles fine, although I do receive a warning, but of course I can live with that.
~~~
share.c:816:21: warning: passing argument 2 of ‘_dos_setvect’ from incompatible pointer type [-Wincompatible-pointer-types]
                     ^
In file included from share.c:11:0:
/usr/ia16-elf/include/dos.h:113:13: note: expected ‘__libi86_isr_t’ but argument is of type ‘__far void (__attribute__((__interrupt__, near_section)) *)(void)’
 extern void _dos_setvect (unsigned __intr_no, __libi86_isr_t __isr);
             ^~~~~~~~~~~~
~~~

Thank you!

**Comment by andrewbird** [comment]
Mmm, this is a strange one. That handler is ending up in the .bss section rather than .text
~~~
.bss            0x0000000000001630      0x11e                                   
                0x0000000000001630                __sbss = .                    
 *(.bss)                                                                        
 .bss           0x0000000000001630       0x76 share.obj                         
                0x0000000000001630                old_handler2f                 
                0x0000000000001634                handler2f                     
 .bss           0x00000000000016a6        0x0 /usr/ia16-elf/lib/libi86.a(dos-freemem.o)
 .bss           0x00000000000016a6        0x0 /usr/ia16-elf/lib/libi86.a(dos-getvect.o)
 .bss           0x00000000000016a6        0x0 /usr/ia16-elf/lib/libi86.a(dos-setvect.o)
~~~

I've tried to steer it by adding a section attribute, but it makes no difference.
Just to sure I hadn't messed things up with my custom tsr linker script, I used the standard /usr/ia16-elf/lib/dos-mtl.ld with the same result.
Finally I removed the .globl handler2f from the asm and although the symbol is gone I can see from the memory allocation that it's still in .bss.

Is there anything else I need to do?

Thank you!

**Comment by andrewbird** [comment]
Same effect with small model too. Here's the code https://github.com/andrewbird/share/commit/2c9d4c64ad914b7db60f4bb96003c8e76a0b6732

**Comment by andrewbird** [comment]
Seems to be caused by `-fno-toplevel-reorder`, without it the function ends up in .text.

**Comment by tkchia** [comment]
Hello @andrewbird,

> Mmm, this is a strange one. That handler is ending up in the .bss section rather than .text

This is probably caused by the positioning of the top-level `__asm` statement.  My guess is that, because the `iregs` variable will go into the BSS segment, and the `__asm` statement comes right after that &mdash; and does not try to switch to a different section &mdash; the `__asm` stuff gets deposited in BSS as well.

(If you compile to assembly language, i.e. use `-S` rather than `-c`, the issue will probably come up clearer.)

I guess one way to solve this &mdash; while still using `-fno-toplevel-reorder` &mdash; is to wrap the assembly code within `.pushsection .text` ... `popsection`.  Another way might be to simply place the declaration and `__asm` statement for `handler2f` right after a function, but this approach is kind of iffy.

Thank you!

**Comment by andrewbird** [comment]
I'm making a little progress.
- I switched to nasm for the assembly code and wrote a wrapper that sorts out the registers for the C code.
- I then ran up against problems as whilst in the C code it wanted to access things via SS register, which I think it assumed was the same as DS. I tried the various compiler options and/or function attributes to break this association, but had little success.
- I created a minimal stack (64 bytes) at the end of heap, which so far seems to be enough.
- It is no longer crashing, but at the moment still not properly functional.

Here's the latest https://github.com/andrewbird/share/commit/f1a6ad5459dc1842b832919fb46c6e9b088057f2

Thank you!

**Comment by andrewbird** [comment]
Seems to be working now, I needed to save and restore things in the right order with segment prefixes where necessary.
https://github.com/andrewbird/share/commit/acf575766edbd446aa1b465a646c2d68f003a5b2

Thank you!

**Comment by tkchia** [comment]
Hello @andrewbird,

You can also try using the `no_assume_ss_data` function attribute to tell GCC that a function may be called with `ss` &#8800; `ds`.  This feature is still rather experimental though (mainly because its internal implementation is very hacky).

Thank you!

**Comment by andrewbird** [comment]
Hello @tkchia,
   Yes I tried that but the interrupt handler makes library calls and the compiler gave me errors (sorry I can't remember exactly which ones now!), presumably due to those functions not having the attribute as well.
  I updated the branch again, minimising the changes to the C and moving some vars from .data to .bss.

The final scores are

Type|Turbo C|Gcc ia16
------|----------|-----------
File size | 6352 | 6684
Resident memory size | 0x0242 | 0x0214
