### ISSUE TITLE
`_dos_*()` I/O family functions

### ISSUE THREAD

**Issue by andrewbird** [tkchia/libi86#8]
Hello @tkchia, I wonder if you might implement the `_dos_*()` I/O family functions as provided by Watcom (and DJGPP)? Currently you have implemented:
- [x] `_dos_close()`
- [x] `_dos_commit()`
- [x] `_dos_creat()`
- [x] `_dos_creatnew()`
- [x] `_dos_open()`
- [x] `_dos_read()`
- [x] `_dos_write()`

Thank you for your consideration!

**Comment by tkchia** [comment]
@andrewbird : OK.

**Comment by andrewbird** [comment]
Hi @tkchia, thanks for all the work you are putting into this. I see you have implemented all of the functions I've asked for now, when do you think a new package with them in will be available in the PPA?

Thank you!

**Comment by andrewbird** [comment]
Thank you for the PPA update. A quick test shows that `_dos_open()`, `_dos_write()` and `_dos_read()` are working for me.

Thanks again!
